import type { NextPage } from 'next'
import Head from 'next/head'
import clsx from 'clsx';
import HeroDrawings from '../components/Hero/HeroDrawings';
import useDeviceSize from '../utils/useDeviceSize';
import Header from '../components/Header';
import Bee from '../components/Hero/Bee';
import Container from '../components/Container';
import Layout from '../components/Layout/Layout';
import { HeroPrimaryButton } from '../components/Buttons';
import Pricing from '../components/Pricing';
import SingleLine from '../components/Hero/SingleLine';
import dict from '../components/dict';

const Home: NextPage = () => {
  const { isMobile } = useDeviceSize();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={clsx('overflow-x-hidden')}>
        <>
          <Bee />
          <Container className={clsx('h-[calc(100vh+50px)]')} fadeOut>
            <div className='flex flex-col justify-center items-center text-center h-[75%] sm:h-[85%]'>
              <Layout>
                {/* <h1>Beautiful SaaS landing pages<br />that'll convert quickly</h1> */}
                {/* <h1 >Your SaaS needs a landing page<br />that will convert</h1> */}
                <h1>{dict.hero.header}</h1>
                <h2 className='mt-4'>{dict.hero.subheader}</h2>
                <HeroPrimaryButton text="See plans" className="min-w-[250px] px-[48px] py-[20px]" />
                <h2 className='mt-12'>{dict.hero.subheader2}</h2>
              </Layout>
            </div>
            <HeroDrawings />
          </Container>
          <Container fadeIn>
            <Layout>
              <h3 className='mt-20'>The weight of converting, lifted off your shoulders</h3>
              <div className="flex mt-36">
                {[
                  {
                    icon: () => <div></div>,
                    title: dict.section1.triad[0].title,
                    description: dict.section1.triad[0].description
                  },
                  {
                    icon: () => <div></div>,
                    title: dict.section1.triad[1].title,
                    description: dict.section1.triad[1].description
                  },
                  {
                    icon: () => <div></div>,
                    title: dict.section1.triad[2].title,
                    description: dict.section1.triad[2].description
                  }
                ].map(ele => (
                  <div key={ele.title} className='flex flex-col basis-1/3 items-center'>
                    <>{ele.icon}</>
                    <h4>{ele.title}</h4>
                    <p className="mt-2">{ele.description}</p>
                  </div>
                ))}
              </div>
              <h3 className='mt-28'>{dict.section2.header1}</h3>
              <p className='text-center m-auto max-w-[600px] mt-10'>{dict.section2.description1}</p>

              <h3 className='mt-28'>{dict.section2.header2}</h3>
              <p className='text-center m-auto max-w-[600px] mt-10'>{dict.section2.description2}</p>
              <SingleLine />
              <p className='flex justify-center text-left'>{dict.section2.bullets2}</p>
              <h3 className='mt-28'>{dict.section2.header3}</h3>
            </Layout>
          </Container>

          <Container>
            <Layout>
              <h3 className='mb-10'>Plans</h3>
                <Pricing />
            </Layout>
          </Container>
        </>
      </main>
    </>
  )
}

export default Home
