import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/pages/index.module.css';
import clsx from 'clsx';
import heroDrawings from '../components/Hero/heroDrawings';
import useDeviceSize from '../utils/useDeviceSize';
import useBrowserName from '../utils/useBrowserName';
import Header from '../components/Header';
import Texture from '../components/Texture';
import Bee from '../components/Hero/Bee';
import Container from '../components/Container';
import Layout from '../components/Layout/Layout';

const Home: NextPage = () => {
  const { isMobile } = useDeviceSize();
  const browserName = useBrowserName();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header variant='primary' />
      <main className={clsx('overflow-x-hidden')}>
        <>
          <Bee />
          <Container className={clsx('h-[calc(100vh+50px)]')} fadeOut>
            <div className='flex flex-col justify-center items-center text-center h-[75%] sm:h-[85%]'>
              <Layout>
                {/* <h1 className='text-6xl tracking-normal leading-tight font-bold'>Beautiful SaaS landing pages<br />that'll convert quickly</h1> */}
                {/* <h1 className='text-4xl sm:text-6xl tracking-normal !leading-tight font-bold'>Your SaaS needs a landing page<br />that will convert</h1> */}
                <h1 className='text-4xl sm:text-6xl tracking-normal !leading-tight font-bold'>Your SaaS needs landing pages<span id="beeLineDestination">&#8203;</span><br />and we <span className='font-extrabold'>love</span> building them</h1>
                <h2 className='mt-4 text-xl tracking-normal leading-tight font-light'>and we'll build the whole thing</h2>
                <div className={clsx(styles['button-outline'], 'mt-10 z-10')}>
                  <button className={clsx(styles['hero-button'])}>
                    <p className={clsx('text-[#f8edeb] p-0 text-lg leading-none font-bold tracking-wide')}>See plans</p>
                  </button>
                </div>
                <h2 className='mt-12 text-xl tracking-normal leading-tight font-light'>A SaaS landing page subscription that'll convert quickly</h2>
              </Layout>
            </div>
            <div className='overflow-hidden absolute top-0 bottom-0 left-0 right-0'>
              {heroDrawings[isMobile ? "mobile" : "desktop"].map(({ Component, size, ...position }, i) => (
                <Component key={"hero-key-" + i} style={{ height: size, width: size, position: "absolute", opacity: 0.8, zIndex: 1, ...position }} />
              ))}
            </div>
          </Container>
          <Container fadeIn>
            <Layout>
              <h2 className='mt-28 text-center text-4xl font-bold'>A massive weight just got lifted off your shoulders</h2>
              <div className="flex">
                <div className='flex flex-col basis-1/3 items-center'>
                  <h3><b>Totally async</b></h3>
                  <p>We deliver products directly to you</p>
                </div>
                <div className='flex basis-1/3 items-center'>

                </div>
                <div className='flex basis-1/3 items-center'>

                </div>
              </div>
              <h2 className='mt-28 text-center text-4xl text-[#1f2d3d] font-bold'>You just got a lot leaner</h2>
            </Layout>
          </Container>
        </>
      </main>
      {/* <svg>
        <filter id='roughpaper'>
          <feTurbulence type="fractalNoise" baseFrequency='0.04' result='noise' numOctaves="5" />

          <feDiffuseLighting in='noise' lightingColor='#F8EDEB' surfaceScale='0.5'>
            <feDistantLight azimuth='45' elevation='60' />
          </feDiffuseLighting>
        </filter>
      </svg> */}

    </>
  )
}

export default Home
